jaegertracing/documentation

docs/client_libraries.md, docs/getting_started.md
Corrected 'walkthrough' spelling on `getting_started.md` page. 
Fixed typos found in 'client_libraries.md' page.
Signed-off-by: Pooja Gadige <poojagadige@gmail.com>
=> Fix spelling error(s) and typos.

content/docs/client-libraries.md, data/clients.yaml, themes/jaeger-docs/layouts/shortcodes/clientsTable.html, themes/jaeger-docs/layouts/shortcodes/featuresTable.html
Fixes #38 
@yurishkuro The YAML file defining the clients is currently incomplete but otherwise I think this is more or less what you were asking for.
* [Features table](https://deploy-preview-39--jaegertracing.netlify.com/docs/client-libraries/#client-library-features)
* [Libraries table](https://deploy-preview-39--jaegertracing.netlify.com/docs/client-libraries/#official-libraries)
=> Add tables for supported clients and client features

.editorconfig, Makefile, scripts/install-hugo.sh
Fixes #36 
Currently, the macOS setup involves using Homebrew to install Hugo. The drawback, however, is that you can't install specific versions directly via Homebrew, which leads to a variety of potential issues. This PR adds an installation script for specific versions of Hugo (as well as different platforms...I'll add Linux setup later).
=> Add version-specific Hugo installation script

.editorconfig, Makefile, content/docs/_index.md, content/docs/architecture.md, content/docs/client-libraries.md, content/docs/features.md, content/docs/getting-started.md, content/docs/sampling.md, data/definitions.yaml, themes/jaeger-docs/layouts/partials/meta.html, themes/jaeger-docs/layouts/shortcodes/definition.html, themes/jaeger-docs/layouts/shortcodes/tip.html, themes/jaeger-docs/package.json, themes/jaeger-docs/source/sass/elements.sass, themes/jaeger-docs/source/sass/style.sass, themes/jaeger-docs/source/sass/variables.sass
This adds hoverable tooltips for definitions of key terms (span, trace, etc.). At the moment I've sprinkled just a few throughout. As the site grows, though, I think that giving readers easy access to terminological definitions will become increasingly important.
For an example hover over the words "span" and "trace" (in beige) in the first paragraph of [this doc](https://deploy-preview-50--jaegertracing.netlify.com/docs/sampling/).
=> Add hoverable tooltips for definitions

content/docs/deployment.md
=> Add documentation about --memory.max-traces

content/docs/getting-started.md
Current command to run the backend in Getting Started does not specify the container name as jaeger. HotROD example is linked to container name jaeger so it fails to connect to the backend.
Signed-off-by: Oguz Pastirmaci <oguzp@microsoft.com>
=> Set container name as jaeger in Getting Started

content/docs/getting-started.md
The '-e' parameter was not next to the environment variable, and caused the command to fail.
=> Fixed incorrect docker run example

content/docs/deployment.md
The ports exposed by the collector do not specify which Thrift protocol should be used when communicating with them. Based on reading the Java client codebase, it appears that HTTP over port 14268 expects [Binary Thrift](https://github.com/jaegertracing/jaeger-client-java/blob/dfb9d8b9dc849f2e6f880b44b26fb77dfc894a02/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/HttpSender.java#L42)
=> Adds protocol note to ports exposed by Collector

Makefile, config.toml
Apparently a regression was introduced in a handful of Hugo versions that broke setting the theme via the `--theme` flag. These changes fix for now and will be rendered superfluous by #102 (but best to un-break things in the meantime).
=> Fix Hugo build

content/docs/deployment.md, data/clients.yaml
Signed-off-by: Prakriti <prakritibansal98@gmail.com>
-Resolves #105 
-Add 128bit trace ID support as a feature on Client Features
=> Add 128bit trace ID support as a feature on Client Features

themes/jaeger-docs/assets/sass/pages.sass
This PR add an css attribute to `.page--docs .nav` to break the nave item into new line in case the text is long. It will make web page display more reasonable in 1366x768 screen resolution.
Resolves #115
=> Fix Nav UI's issue

content/docs/deployment.md
Signed-off-by: Michael Irwin <mikesir87@gmail.com>
- Fixing typo
- Fixing typo of env variable. Nothing major 😄
=> Fix env variable misspelling in cassandra deploy example

themes/jaeger-docs/layouts/partials/meta.html
I learned the other day that OpenGraph tags need to be `<meta name="..." content="...">` rather than `<meta property="..." content="...">`. This PR should improve the SEO picture a bit.
=> Fix OpenGraph tags

themes/jaeger-docs/layouts/index.redirects
For reasons I don't quite understand, Hugo is generating a `/docs` page that isn't supposed to be there. So I've added a redirect that will send `/docs` to `/docs/LATEST_VERSION`.
=> Main docs page redirect

config.toml, data/download.yaml, netlify.toml, themes/jaeger-docs/layouts/shortcodes/binaries.html, themes/jaeger-docs/layouts/shortcodes/dockerImages.html
cc @yurishkuro
Addresses issue #147. I haven't yet come up with a good way of doing a combined "Components" table but we can save that for a future PR. There are also some missing Docker image descriptions. Feel free to provide those here in the PR discussion or do a follow-up PR (or just push commits).
The new download page is here:
https://deploy-preview-148--jaegertracing.netlify.com/download/
=> Download page follow-up

content/download/_index.md, data/download.yaml, themes/jaeger-docs/layouts/shortcodes/binaries.html, themes/jaeger-docs/layouts/shortcodes/priorBinaries.html
Addresses issue #151 by showing only the most recent version in the downloads table. Prior versions are listed in a separate list with links to the GitHub releases page.
Preview:
https://deploy-preview-152--jaegertracing.netlify.com/download/
=> Display latest version only in binaries table

config.toml, themes/jaeger-docs/layouts/404.html, themes/jaeger-docs/layouts/index.redirects, themes/jaeger-docs/layouts/partials/docs/header.html, themes/jaeger-docs/layouts/partials/home/hero.html, themes/jaeger-docs/layouts/partials/navbar.html, themes/jaeger-docs/layouts/shortcodes/dockerImages.html
This PR removes the need to specify the latest version in the Hugo config. Instead, the latest can be inferred from the directory structure, i.e. Hugo will automatically know that 2.5 is the latest among versions 2.3, 2.4, and 2.5.
Just a little trick that I figured out working on another project.
=> Auto-infer latest from directory structure

config.toml, data/download.yaml, themes/jaeger-docs/layouts/index.redirects, themes/jaeger-docs/layouts/partials/docs/header.html, themes/jaeger-docs/layouts/partials/navbar.html, themes/jaeger-docs/layouts/shortcodes/binaries.html
This PR changes the versioning scheme behind the docs from an implicit scheme (that infers existing versions and "latest" from the subdirectories of `content/docs`) to an explicit scheme (in which all versions and "latest" are assigned in the site configuration).
@yurishkuro This should address the concerns you raised previously.
=> Use explicit versioning scheme

data/clients.yaml
This PR documents 128bit trace id feature for the java client.
128 bit trace id is now available on java client.
=> Document 128bit trace ID support on Java Client as available

content/docs/1.6/deployment.md, content/docs/1.7/deployment.md, content/docs/1.8/deployment.md
Resolves: https://github.com/jaegertracing/jaeger-ui/issues/7
=> Add archive traces UI configuration

content/docs/next-release/getting-started.md
* Remove "Running Individual Jaeger Components" that suggests to run from source (fixes #194)
* Remove Client Libraries section, since we mention client libraries in the very first section Instrumentation.
* Reorder the HotROD section to be
* intro
* features
* prerequisites
* running
* Reduce nesting of HotROD sections
preview: https://deploy-preview-195--jaegertracing.netlify.com/docs/next-release/getting-started/#SampleApp:HotROD
=> Clean-up and refactor Getting Started page

themes/jaeger-docs/layouts/404.html, themes/jaeger-docs/layouts/index.html, themes/jaeger-docs/layouts/partials/home/hero.html, themes/jaeger-docs/layouts/shortcodes/dockerImages.html
Since release of 1.10 some of the pages were still pointing to 1.9 due to the use of readDir / sort.
=> Fix references to latest version

content/docs/next-release/deployment.md
=> Use gprc reporter by default

themes/jaeger-docs/layouts/partials/meta.html
I think this was inadvertently added during a merge.
cc @yurishkuro
=> Remove redundant canonical tag

themes/jaeger-docs/layouts/partials/navbar.html
Temporary fix for #224
The main Docs items will be accessible on mobile devices, but sub-items like Client Features (a child of Client Libraries) are still not accessible.
Also adds links to the main & docs repos to the Project menu.
cc @lucperkins
=> Always display Docs in the navbar

content/docs/1.11/deployment.md, content/docs/next-release/deployment.md
Signed-off-by: Annanay <annanay.a@media.net>
- Documentation for jaegertracing/jaeger#1396
=> Document support for agent level tags

themes/jaeger-docs/layouts/_default/single.html
The HTML title tag is wrong for single-pages. It's always "Jaeger - Downloads", when it should use the page's "Title" property:
=> Fixed page title for single pages

themes/jaeger-docs/layouts/partials/navbar.html
This PR provides a link to the new [branding page](https://branding.cncf.io/projects/jaeger) for Jaeger.
=> Provide link to branding site

config.toml, themes/jaeger-docs/layouts/partials/docs/header.html, themes/jaeger-docs/layouts/partials/docs/panel.html, themes/jaeger-docs/layouts/partials/footer.html, themes/jaeger-docs/layouts/partials/navbar.html
The GitHub and Twitter icons in the navbar are currently not showing on the deployed site. This PR fixes that.
=> Fix navbar social icons

content/docs/1.11/features.md, content/docs/next-release/features.md
Referencing the jaeger operator in the features/cloud native deployment section - currently only mentions templates and helm chart.
Added link to the jaeger-operator repo.
=> Reference jaeger operator in features/cloud native section

content/docs/1.12/monitoring.md, content/docs/next-release/monitoring.md
Signed-off-by: mwieczorek <wieczorek-michal@wp.pl>
`/metrics` are exposed on different ports than in docs.
Changed port numbers
=> Fix port numbers for monitoring endpoints

content/docs/1.10/client-libraries.md, content/docs/1.11/client-libraries.md, content/docs/1.12/client-libraries.md, content/docs/1.6/client-libraries.md, content/docs/1.7/client-libraries.md, content/docs/1.8/client-libraries.md, content/docs/1.9/client-libraries.md, content/docs/next-release/client-libraries.md
- Using wrong terminology for case styles
- Change "snake-case" to "kebab-case"
The difference is:
kebab-case vs. snake_case
See: https://en.wikipedia.org/wiki/Letter_case#Special_case_styles
=> Fix terminology - change from "snake-case" to "kebab-case"

content/docs/1.13/deployment.md, content/docs/next-release/deployment.md
I got an email from "Got.Media", asking to add a link to NGINX' website from the `Deployment` page, where we mention them. I think it's a fair request.
=> Link NGINX to its website

themes/jaeger-docs/layouts/partials/home/hero.html
We haven't published a newsletter since Oct 2018, it looks like of sad on the home page above the fold.
This PR comments out the code for it.
cc @objectiser
=> Disable Newsletter button as it is stale

content/docs/1.13/frontend-ui.md, content/docs/1.13/operator.md, content/docs/next-release/frontend-ui.md, content/docs/next-release/operator.md
Missing docs regarding the `linkPatterns` element in the UI configuration, as discussed in blog post: https://medium.com/@mwieczorek/custom-links-in-jaeger-ui-3479f72bb815
Added section in frontend-ui doc and cross-referenced from the operator doc page.
=> Add link patterns info to docs

themes/jaeger-docs/layouts/index.json, themes/jaeger-docs/layouts/partials/navbar.html, themes/jaeger-docs/layouts/partials/search.html
This PR makes two improvements to the search bar:
* It limits the number of results to 8, which prevents the dropdown from taking up too much vertical space
* It appends a `*` to the search term, which provides, in my opinion, a much more responsive search experience
=> Search bar improvements

content/docs/next-release/operator.md
Once jaegertracing/jaeger-operator#476 is merged, this PR adds a basic documentation about the upgrade process.
=> Added text about managed upgrades in the operator

content/docs/next-release/features.md, content/roadmap.md
=> Add Zipkin protobuf support and remove zipkin from roadmap

data/clients.yaml
- https://github.com/jaegertracing/jaeger/issues/858
- Update the matrix as Python and Node clients now have support for 128bit traceid
- https://github.com/jaegertracing/jaeger-client-python/releases/tag/v4.0.0
- https://github.com/jaegertracing/jaeger-client-node/releases/tag/v3.16.0
=> Update 128bit_trace_id from client feature matrix

content/docs/next-release/client-libraries.md
If we want to remain future-compatible with W3C
=> Clarify that span ID of 0 is not valid

content/docs/1.14/deployment.md, content/docs/1.14/getting-started.md, content/docs/next-release/deployment.md, content/docs/next-release/getting-started.md
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
- Zipkin Proto support was added in Jaeger1.14. This PR updates Getting Started docs for that.
- Refer https://github.com/jaegertracing/jaeger/pull/1695 and https://github.com/jaegertracing/jaeger/releases/tag/v1.14.0. We've missed this change in https://github.com/jaegertracing/documentation/pull/295
- Update `1.14/getting-started.md`
=> Update docs for Zipkin Proto support

content/docs/1.14/operator.md, content/docs/next-release/operator.md
Setting up the security context to enable host port binding in openshift is discussed in the section on installing in openshift, but not in the section specific to using agent as daemonset.
This PR adds the same description in the agent daemonset section - may want to consider removing it from the "Installing the Operator on OKD/OpenShift" section so only discussed in the context of using a daemonset agent.
@JStickler thoughts?
=> Add openshift specific permission setup in daemonset agent section

content/docs/next-release/deployment.md, content/docs/next-release/windows.md
This addition to the docs outlines the process to set up Jaeger services using NSSM on Windows.
Please see: https://github.com/jaegertracing/jaeger/issues/1890#issuecomment-548806867
Resolves jaegertracing/jaeger#1890
Signed-off-by: Scott Kaye <pgreviews@gmail.com>
- Users have been asking how to run Jaeger as a Windows service, manageable with `sc`.
- Added simple directions on how to set up NSSM to solve this problem.
=> Added directions to set up Windows service

content/docs/1.12/deployment.md, content/docs/1.13/deployment.md, content/docs/1.14/deployment.md, content/docs/next-release/deployment.md
The previous argument `--jaeger-tags` was incorrect it should be `-jaeger.tags`. 
Also add to the example that multiple tags can be added from the same argument.
=> Fix agent tags configuration argument

content/docs/next-release/operator.md
This commit adds a new section to 'Configuring the CRD' with examples on how to disable the Ingress and how to add a TLS certificate to it.
Issue #307
Relates to https://github.com/jaegertracing/jaeger-operator/pull/681
Signed-off-by: Cedric Kring <cedric@kring-online.de>
=> Document secretName support for Ingress TLS

content/docs/next-release/operator.md
Docs to accompany https://github.com/jaegertracing/jaeger-operator/pull/738
=> Add information about self provisioned Kafka

content/docs/next-release/operator.md
This PR documents what's needed to get traces out of the Jaeger Operator. This new feature is being added as part of jaegertracing/jaeger-operator#738.
=> Added doc about tracing the operator

content/docs/1.15/faq.md, content/docs/next-release/faq.md
People often ask why they need to run the agent.
https://stackoverflow.com/questions/59153293/advantages-of-using-jaeger-agent
=> Add FAQ about jaeger-agent

content/docs/1.16/operator.md, content/docs/next-release/operator.md
Resolves #336 
https://deploy-preview-338--jaegertracing.netlify.com/docs/next-release/operator/#self-provisioned
Once approved I will copy it to current and older releases.
=> Document self-provisioned Elasticsearch example CR

content/docs/next-release/deployment.md, content/docs/next-release/features.md
Missing new storage plugin - logz.io
Add a link to jaeger-logzio repo
=> Add logzio storage plugin

content/docs/next-release/sampling.md
- adds per-operation strategies to the `default_strategy` section of the sample configuration
- reflects changes in PR https://github.com/jaegertracing/jaeger/pull/1749 / ticket https://github.com/jaegertracing/jaeger/issues/1748
=> Show default sampling strategy with per-operation sampling

content/docs/1.14/architecture.md, content/docs/1.15/architecture.md, content/docs/1.16/architecture.md, content/docs/next-release/architecture.md
Adding "APIs" submenu back to the lefthand menu - removed after 1.13 release for some reason?
Add apis.md as child of architecture page.
=> Add back api sub-menu

data/clients.yaml
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
- Documentation for https://github.com/jaegertracing/jaeger-client-cpp/issues/178
-
=> Update cpp client features

content/docs/1.16/getting-started.md, content/docs/next-release/getting-started.md
It was missing in the docker run statement but mentioned below in the exposed ports.
=> Added port forword for grpc port

content/docs/next-release/frontend-ui.md
Related to jaeger-ui PR https://github.com/jaegertracing/jaeger-ui/pull/511
I've added documentation for search.maxLimit input. I've noticed that maxLookback didn't have any documentation so I added.
Let me know if it's ok
Thank you so much!
Gabriel Fernando Dyck
=> Add jaeger-ui search configuration jaegertracing/jaeger-ui#511

content/docs/next-release/operator.md
Included also what happens when multiple operators are watching the same namespace.
=> Added intro to the installation section

data/clients.yaml
- The doc page with the data format/transport seems to be outdated. I went over the listed clients and tried to sync the data based on different types of evidence (code, test, example or documentation), resulting in this PR.
I also checked which Thrift encoding formats are supported by each client, but we don't seem to be recording this anywhere. Is this something we'd want to record somewhere?
Client | Compact | Binary
-- | -- | --
Java | ✔️ | ✔️
Go | ✔️ | ❌
C# | ✔️ | ❌
C++ | ✔️ | ❌
Python | ✔️ | ❌
Node | ❌ | ✔️
=> Updated the data format/transport table for clients

Makefile
Following up on concerns raised in #363
=> Change htmltest installation link to GitHub URL

Makefile, netlify.toml, themes/jaeger-docs/layouts/404.html, themes/jaeger-docs/layouts/_default/single.html, themes/jaeger-docs/layouts/_default/taxonomy.html, themes/jaeger-docs/layouts/_default/terms.html, themes/jaeger-docs/layouts/docs/single.html, themes/jaeger-docs/layouts/download/list.html, themes/jaeger-docs/layouts/index.html, themes/jaeger-docs/layouts/index.redirects, themes/jaeger-docs/layouts/partials/css.html, themes/jaeger-docs/layouts/partials/docs/header.html, themes/jaeger-docs/layouts/partials/docs/panel.html, themes/jaeger-docs/layouts/partials/footer.html, themes/jaeger-docs/layouts/partials/home/articles.html, themes/jaeger-docs/layouts/partials/home/features.html, themes/jaeger-docs/layouts/partials/javascript.html, themes/jaeger-docs/layouts/partials/meta.html, themes/jaeger-docs/layouts/partials/navbar.html, themes/jaeger-docs/layouts/shortcodes/binaries.html, themes/jaeger-docs/layouts/shortcodes/cli/tools-list.html, themes/jaeger-docs/layouts/shortcodes/clientsTable.html, themes/jaeger-docs/layouts/shortcodes/definition.html, themes/jaeger-docs/layouts/shortcodes/dockerImages.html, themes/jaeger-docs/layouts/shortcodes/featuresTable.html
This PR updates the site to the latest version of Hugo and makes a few changes related to the site build:
* It minifies HTML output, which allows for more compact assets and should speed up page load times a little bit
* It moves the Netlify build commands into the Makefile
* It eliminates markup that's no longer necessary given HTML minification (i.e. `{{- ... -}}` can now be `{{ ... }}` in most cases)
=> Update Hugo version

content/docs/1.17/operator.md, content/docs/next-release/operator.md
- Documentation for jaegertracing/jaeger-operator#916
=> Added documentation about cluster-wide permissions for the operator

content/docs/1.17/operator.md, content/docs/next-release/operator.md
Signed-off-by: Eric Wohltman <eric.wohltman@gmail.com>
- This PR is in support of Issue https://github.com/jaegertracing/jaeger-operator/issues/944
- This change includes updates for how to include the Jaeger Agent sidecar manually for controllers other than `Deployments`
=> Add manual sidecar definition documentation and example

content/docs/1.17/apis.md, content/docs/next-release/apis.md
Now the links for collector.proto and query.proto in the
docs/1.17/apis [page](https://www.jaegertracing.io/docs/1.17/apis/#protobuf-via-grpc-stable) will triger 404 error, so I modify the links to
jump to the proper location in jaeger-idl repository.
Signed-off-by: Panlichen <plch368@qq.com>
- Now the links for collector.proto and query.proto in the docs/1.17/apis [page](https://www.jaegertracing.io/docs/1.17/apis/#protobuf-via-grpc-stable) will triger 404 error.
- Modify the links to jump to the proper location in jaeger-idl repository.
=> Modify links to prevent 404 error

content/docs/1.13/operator.md, content/docs/1.14/operator.md, content/docs/1.15/operator.md, content/docs/1.16/operator.md, content/docs/1.17/operator.md, content/docs/next-release/operator.md
Resolves #386 
- Jaeger Operator default sampling configuration uses integer value type instead of double
- Value of 50 was changed to .5
=> Fix value type in Jaeger Operator default sampling example

content/docs/1.18/deployment.md, content/docs/next-release/deployment.md
It gets a weird anchor `#configuration-3` and we already have a top `Configuration Options` section.
=> Remove redundant Configuration section

content/docs/1.18/apis.md, content/docs/1.18/deployment.md, content/docs/next-release/apis.md, content/docs/next-release/deployment.md
Tchannel was removed in 1.18.0 https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#backend-changes-2
=> Remove tchannel collector port

content/docs/next-release/operator.md
- Every now and then we have a question about which Kubernetes versions the Operator should support. This PR documents the current consensus. See https://github.com/jaegertracing/jaeger-operator/issues/1109#issuecomment-653401855
=> Added support expectation for Kubernetes versions

content/docs/next-release/performance-tuning.md
- Added a reference to a useful metric for performance tuning.
- While doing research on dropped spans I found `jaeger_agent_client_stats_spans_dropped_total` and felt like it should be  included in this doc.
Should I PR this change against all past versions of this doc?
=> Added note about jaeger_agent_client_stats_spans_dropped_total

content/docs/next-release/operator.md
~~Associated PR: https://github.com/jaegertracing/jaeger-operator/pull/1103~~
Associated PR: https://github.com/jaegertracing/jaeger-operator/pull/1115
This PR updates the documentation to mention the capability to specify imagePullSecrets for Jaeger resources.
=> Add image pull secrets to Jaeger resources

content/docs/next-release/opentelemetry.md
This flag is wrong and causes an error when try to use it.
documentation typo
--es.server.urls  ->  --es.server-urls
=> Fix --es.server-urls flag example

data/clients.yaml
The Python client supports both the `jaeger-debug-id` and `jaeger-bagage` headers. 
See these constant definitions:
https://github.com/jaegertracing/jaeger-client-python/blob/7984b2872b09a36b7ea0ae6479035ed61666af30/jaeger_client/constants.py#L42-L51
and the code to handle text map extraction (which is responsible for HTTP header handling too) ; the constants above have been propagated to this section as `self.debug_id_header` and `self.baggage_header`:
https://github.com/jaegertracing/jaeger-client-python/blob/7984b2872b09a36b7ea0ae6479035ed61666af30/jaeger_client/codecs.py#L91-L136
and finally the code that handles setting the debug tag when a debug header was present:
https://github.com/jaegertracing/jaeger-client-python/blob/7984b2872b09a36b7ea0ae6479035ed61666af30/jaeger_client/tracer …
=> Update Python header support info

content/docs/1.18/operator.md, content/docs/1.19/operator.md, content/docs/next-release/operator.md
There is no `enabled` option in the rollover spec https://godoc.org/github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1#JaegerEsRolloverSpec
=> Remove rollover enabled option

content/report-security-issue.md
- Currently listed server seems to be having problems
- Inconsistencies in the request to encrypt messages
- Use the server pool for the keyserver, even if the TLS certs are typically not matching the request
- Clarified that all communication with us should preferrably be encrypted
=> Adjusted the info in the security page

themes/jaeger-docs/assets/js/app.js, themes/jaeger-docs/assets/sass/copy-button.sass, themes/jaeger-docs/assets/sass/style.sass
Hi, 
This resolves #444 .
I tried adding a copy button on the right top corner of all the code snippets. 
A preview 
Signed-off-by: Shreya Gupta <shreyagupta3011@gmail.com>
=> Add copy to clipboard button for code snippets on Get started page.

content/docs/next-release/opentelemetry.md
This makes it easier for users to configure their OpenTelemetry clients.
Mention that the OTLP receiver is on by default, and which port it listens on.
My understanding of the previous text was that I would have to configure it myself.
I found its configuration in the source code here: https://github.com/jaegertracing/jaeger/blob/3c0505fc779e2d054c23304134bef4f22ce9ce75/cmd/opentelemetry/app/defaultconfig/default_config.go#L163
and here: https://github.com/open-telemetry/opentelemetry-collector/blob/7dd853ab95834619169360fa2abbb981af42f061/receiver/otlpreceiver/factory.go#L62
=> Add OTLP receiver port to OpenTelemetry page

travis/gen-cli-data.py, travis/release.sh
- Release is currently broken: https://travis-ci.com/github/jaegertracing/documentation/builds/201798015
```
+python ./travis/gen-cli-data.py 1.21 /tmp/cli-docs-MgMaiwdl
Traceback (most recent call last):
File "./travis/gen-cli-data.py", line 12, in <module>
with open("data/cli/%s/config.json" % jaeger_ver, 'r') as f:
```
These changes allow me to run the build successfully locally in "dry run" mode.
`with open("%s/data/cli/%s/config.json" % (output_path, jaeger_ver), 'r') as f:`
The python script needs to be updated to point to the new temp path where the files are copied and then generated.
`chmod 644 -R ${cliDocsTempDir}`
This was removed b/c the files created by the docker container were owned by root and this command was failing on my local system.  Unsure if this would pass in …
=> Two changes to fix the release process

travis/release.sh
One more fix to the build process.
Build is currently failing with the following.  See: https://travis-ci.com/github/jaegertracing/documentation/builds/201930757
```
./travis/release.sh: line 40: DRY_RUN: unbound variable
```
This is due to `set -u` at the top of the script.  Leaving -u out should be fine.  The lines containing `$TRAVIS_TAG` and `$DRY_RUN` are written in a way that they will behave as expected if they are unset.
=> Ignore unbound vars

travis/release.sh
- Related to #457 
- Removed the other option that will cause a script to fail if there are unbound variables.
=> Remove the other option that will break on unbound variables

data/clients.yaml
there is a minor typo in the description of `JAEGER_SAMPLER_REFRESH_INTERVAL`
- I corrected the spelling of 'sampling'
=> Fix typo in description of JAEGER_SAMPLER_REFRESH_INTERVAL

content/docs/1.13/operator.md, content/docs/1.14/operator.md, content/docs/1.15/operator.md, content/docs/1.16/operator.md, content/docs/1.17/operator.md, content/docs/1.18/operator.md, content/docs/1.19/operator.md, content/docs/1.20/operator.md, content/docs/1.21/tools.md, content/docs/next-release/operator.md, content/docs/next-release/tools.md
Signed-off-by: Ashmita Bohara <ashmita.bohara152@gmail.com>
Added documentation for tracegen and anonymizer
Also fixed one typo.
=> Add tools page with tracegen and anonymizer

content/docs/1.21/client-libraries.md, content/docs/next-release/client-libraries.md
The old text was incorrectly describing baggage values as always URL-encoded.
=> Clarify baggage value encoding

themes/jaeger-docs/layouts/partials/meta.html
With this change, the latest docs version is used as canonical URL to improve indexing in search engines.
The canonical URL should point to the latest
version of the docs, so Google will index the
most current documentation.
Previous related change: https://github.com/jaegertracing/documentation/pull/440
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method
I copied parts of this canonical-logic for another docs-site and noticed this issue.
=> Use latest docs version for canonical URL

content/docs/1.22/getting-started.md, content/docs/1.22/monitoring.md, content/docs/next-release/getting-started.md, content/docs/next-release/monitoring.md
In v1.22 many deprecated flags were removed, but the docs still mention them. I found & changed a few instances, but there may be others, it's unclear how to find them all.
=> Replace deprecated/removed flags in examples

content/docs/next-release/deployment.md
The first experimental InfluxDB Jaeger plugin has been archived, and new work is active in a new repository.
There is no open issue.
Update one URL in the deployment markdown document.
=> Update link to InfluxDB plugin

content/docs/1.13/operator.md, content/docs/1.14/operator.md, content/docs/1.15/operator.md, content/docs/1.16/operator.md, content/docs/1.18/operator.md, content/docs/1.19/operator.md, content/docs/1.20/operator.md, content/docs/1.21/operator.md, content/docs/1.22/operator.md, content/docs/next-release/operator.md
- There was a dead link to an example yaml in the docs. This updates the link.
=> Fixed a dead link in the operator docs

content/get-in-touch.md
Signed-off-by: albertteoh <albert.teoh@logz.io>
From the ["Getting in touch" page](https://www.jaegertracing.io/get-in-touch/), clicking on the "#jaeger at the CNCF Slack" link results in an error.
I've been [testing a broken link detector in my fork](https://github.com/albertteoh/documentation/actions), but it doesn't pickup on this broken link :( maybe because it returns a 302 HTTP redirect instead of a 404.
=> Fix slack URL

content/docs/1.16/deployment.md, content/docs/1.17/deployment.md, content/docs/1.18/deployment.md, content/docs/1.19/deployment.md, content/docs/1.20/deployment.md, content/docs/1.21/deployment.md, content/docs/1.22/deployment.md, content/docs/next-release/deployment.md
jaeger.tags option has been deprecated in 1.16 (see #1854) and
removed definitively in 1.22 (See #2753)
Signed-off-by: Julien Vey <vey.julien@gmail.com>
=> fix: Replace deprecated (and removed) agent tags option

content/docs/1.13/operator.md, content/docs/1.14/operator.md, content/docs/1.15/operator.md, content/docs/1.16/operator.md, content/docs/1.17/operator.md, content/docs/1.18/operator.md, content/docs/1.19/operator.md, content/docs/1.20/operator.md, content/docs/1.21/operator.md, content/docs/1.22/operator.md, content/docs/next-release/operator.md
- URLs to specific files in [/deploy/examples](https://github.com/jaegertracing/jaeger-operator/tree/master/deploy/examples) folder on the Operator page are broken because the section was moved to [/examples](https://github.com/jaegertracing/jaeger-operator/tree/master/examples).
- Fixed URLs using the up-to-date path
=> fix: use correct operator examples URL

content/docs/1.22/deployment.md, content/docs/next-release/deployment.md
`all-in-one` and `jaeger-query` do not, in fact, listen for grpc on the same port as http.
If you send grpc requests to this port, you get complete garbage back.
Do not tell people to use the wrong port.
```
% docker run -it jaegertracing/jaeger-query:1.22 --help  | fgrep -m1 grpc
--query.grpc-server.host-port string              The host:port (e.g. 127.0.0.1:14250 or :14250) of the query's gRPC server (default ":16685")
```
Especially relevant as [it segfaults if you look at it funny](https://github.com/jaegertracing/jaeger/issues/2996).
=> fix: grpc is not running on the ui port

content/docs/next-release/deployment.md
Signed-off-by: Ashmita Bohara <ashmita.bohara152@gmail.com>
Update documentation with steps to migrate from badger v1 to v3
/cc @jpkrohling
=> Add Badger v1 to v3 migration steps

RELEASE.md
Signed-off-by: Prithvi Raj <p.r@uber.com>
=> Update release doc to clarify steps

content/docs/1.25/getting-started.md, content/docs/next-release/getting-started.md
* Allows the commands to be copied and pasted to the terminal directly
=> Remove `$` prompts from commands in getting-started

Makefile, content/_client_libs/client-features.md, content/_client_libs/client-libraries.md, data/clients.yaml
Part of https://github.com/jaegertracing/jaeger/issues/3362
I am not sure how extensive the matrix of feature compatibility should be. In theory we could use the same format as in https://www.jaegertracing.io/docs/1.27/client-features/. It will involve more work to setup the rendering, but will result in easy to maintain source file and cleaner presentation.
=> Add notice about retiring Jaeger clients

data/cli/1.28/config.json, data/cli/next-release/config.json, scripts/gen-cli-data.py, themes/jaeger-docs/layouts/shortcodes/cli/tools-list.html
- Relates to https://github.com/jaegertracing/jaeger/issues/2954
- Adds support for metrics-storage to the auto-generated documentation.
- Minor improvements:
- Taking advantage of python 3 features such as f-strings along with some simplifications.
- Fix variable names and titles in template.
Generated CLI docs against version 1.28 to allow output comparison.
```
$ diff -q /home/go/src/github.com/albertteoh/documentation/data/cli/1.28/ /tmp/docs/data/cli/1.28
Files /home/go/src/github.com/albertteoh/documentation/data/cli/1.28/config.json and /tmp/docs/data/cli/1.28/config.json differ
Only in /tmp/docs/data/cli/1.28: jaeger-all-in-one-prometheus.yaml
Only in /tmp/docs/data/cli/1.28: jaeger-query-prometheus.yaml
$ diff …
```
=> Add metrics storage support to auto-generated CLI documentation

.github/workflows/ci-release.yml, README.md, RELEASE.md, content/_client_libs/client-features.md, content/get-involved.md, data/clients.yaml, data/download.yaml, scripts/release.sh
- Renames references from master to main in an attempt to fix the [failing release build job](https://github.com/jaegertracing/documentation/runs/4745349895?check_suite_focus=true) on the newly introduced `main` branch.
=> Rename master to main

content/docs/1.27/_index.md, content/docs/1.28/_index.md, content/docs/1.29/_index.md, content/docs/1.30/_index.md, content/docs/1.31/_index.md, content/docs/1.32/_index.md, content/docs/next-release/_index.md, content/docs/next-release/sampling.md
- Fixes #557 
- Removes the adaptive sampling "coming soon" from the main page for all versions since 1.27.
- Adds a short paragraph about using `SAMPLING_STORAGE_TYPE` recently added
=> Adaptive update

content/docs/next-release/_index.md, content/docs/next-release/apis.md, content/docs/next-release/atm.md, content/docs/next-release/deployment.md, content/docs/next-release/features.md, content/docs/next-release/frontend-ui.md, content/docs/next-release/getting-started.md, content/docs/next-release/operator.md, themes/jaeger-docs/layouts/shortcodes/mermaid.html
- Resolves #553
- Adds the Aggregated Trace Metrics documentation, marking it as experimental.
- As [suggested](https://github.com/jaegertracing/documentation/issues/553#issuecomment-1058206739), I have put the majority of content in a single feature-oriented document.
- Updated k8s operator and Jaeger UI config documents with relevant details along with references to the main ATM feature document.
- Architecture diagram implemented with mermaid to allow for easy editing in anticipation of up-coming changes, particularly to the OTEL pipeline configuration.
- The rendered architecture diagram:
=> Add Aggregated Trace Metrics documentation

content/roadmap.md
- https://github.com/jaegertracing/jaeger/issues/2954 was completed. As such, I propose we remove the ATM roadmap item.
=> Remove ATM from roadmap

content/docs/1.22/deployment.md, content/docs/1.23/deployment.md, content/docs/1.24/deployment.md, content/docs/1.25/deployment.md, content/docs/1.26/deployment.md, content/docs/1.27/deployment.md, content/docs/1.28/deployment.md, content/docs/1.29/deployment.md, content/docs/1.30/deployment.md, content/docs/1.31/deployment.md, content/docs/1.32/deployment.md
**Problem**
By following the documentation, the elasticsearch index template would be overridden by the collector. The template create by the collector would not have the ILM policy setup thus stopping the rollover to work.
**Proposal** 
Adding create-index-templates=false will prevent this issue. Having this mentioned in the doc will help people setup ILM without having to debug why the rollover would stop working.
=> Fixing ILM documentation 

content/docs/next-release/spm.md
- Resolves https://github.com/jaegertracing/jaeger/issues/3587
- With metrics available on the metrics reader, this adds troubleshooting tips that incorporate inspecting jaeger metrics.
- Additional troubleshooting advice, by following the flow of data up to its source, is also provided, along with relevant links.
=> Add more troubleshooting tips including metrics

.github/workflows/ci-release.yml, themes/jaeger-docs/layouts/index.json, themes/jaeger-docs/layouts/partials/javascript.html, themes/jaeger-docs/layouts/partials/navbar.html
Temporary workaround for #570:
* do not include non-latest docs into the search index `index.json`
* do not render the Search bar on non-latest docs
* do not load lunr module on non-docs pages
cc @albertteoh
=> Disable search on all docs except latest version

themes/jaeger-docs/layouts/partials/home/articles.html
- Currently, the below blog displays `&amp;` in the article 
https://medium.com/jaegertracing/jaeger-persistent-storage-with-elasticsearch-cassandra-kafka-f3c6c680a58c?source=rss----99735986d50---4
- Strips HTML and returns the plain text version of the provided title string
=> fix: Strips HTML in title

content/_client_libs/client-libraries.md, content/docs/next-release/_index.md, content/docs/next-release/apis.md, content/docs/next-release/architecture.md, content/docs/next-release/features.md, content/docs/next-release/getting-started.md, content/docs/next-release/sampling.md, content/docs/next-release/spm.md
A spring clean-up of the docs to put more emphasis on OpenTelemetry and tone down references to OpenTracing. Mention the OTLP support coming in v1.35 via https://github.com/jaegertracing/jaeger/pull/3701.
I've also simplified the docs by removing the definition/tip short-cuts, which were only used for the words traces/spans, which is largely superfluous. Unfortunately, cannot remove the file `data/definitions.yaml` because older docs versions still refer to them.
=> Give more emphasis to OpenTelemetry

content/docs/1.36/deployment.md, content/docs/next-release/deployment.md
Add Promscale as the supported backend for Jaeger. Promscale can be integrated with Jaeger using gRPC service endpoint with the [support for external gRPC service](https://github.com/jaegertracing/jaeger/pull/3383) released in Jaeger `1.30`.
=> Add Promscale as supported backend for Jaeger

content/docs/next-release/apis.md, content/docs/next-release/deployment.md, content/docs/next-release/faq.md, data/download.yaml
* Add `jaeger-remote-storage` component
* Round up the description of all binaries in one place, above the storage backends section.
Per https://github.com/jaegertracing/jaeger/issues/3835
=> Add description of remote-storage component

content/docs/next-release/deployment.md
- Recent Promscale release i.e. `0.14.0` now natively supports Jaeger write interface. In the past Promscale only supported Jaeger's read path. Now Promscale natively supports Jaeger's both read and write paths.
=> Update Promscale on native Jaeger ingest support

content/download/_index.md
This should wait till the next release, because the signing has not been done on the existing releases.
=> Add instructions for validating checksums and signatures

content/docs/next-release/spm.md
- Resolves #616
- Adds OTEL SDK, OTLP exporter, Jaeger collector and trace storage to architecture diagram to provide a more complete picture of the components involved for SPM.
Rendered diagram:
=> Add SDK, collector and trace storage in arch diagram

content/docs/next-release/deployment.md
This PR solves the lack of documentation regarding the use of ScyllaDB as a drop-in replacement for Cassandra in Jaeger tracing server deployment. By providing clear instructions on how to configure the CASSANDRA_SERVERS environment variable, users can easily switch to ScyllaDB for enhanced performance and compatibility without any additional changes to their existing setup.
This PR adds a note to the Jaeger tracing server deployment documentation, explaining how to configure the system to use ScyllaDB as a drop-in replacement for Cassandra by simply updating the CASSANDRA_SERVERS environment variable to point to ScyllaDB hosts.
=> add a note about scylladb as a storage backend to deployment.md

content/docs/next-release/operator.md
As stated in issue #612, this commit replaces the Capitalized component names with binary names in operator.md file 
- Use of binary name, such as **jaeger-agent**, **jaeger-collector**, **jaeger-query**
- Remove prefix "the"
- Make plural forms by adding s after the bold portion, i.e. **jaeger-collector**s == jaeger-collectors
- Similarly, make possessive forms by adding 's after the bold portion, i.e. **jaeger-collector**'s == jaeger-collector's
=> Consistent Naming For Jaeger Components

content/docs/1.44/troubleshooting.md, content/docs/1.45/troubleshooting.md, content/docs/next-release/troubleshooting.md
- Upstream documentation in https://github.com/open-telemetry/opentelemetry-specification repository was relocated, leaving Jaeger documentation with broken links.
- We are updating upstream URLs in Jaeger configuration.
=> Fix OTEL specification sdk-environment-variables document URL

content/mentorship-for-mentees.md, content/mentorship-for-mentors.md, themes/jaeger-docs/layouts/partials/navbar.html
- We are missing mentorship onboarding documentation, to offer guidance to those new to making open source contributions.
- Add separate "For Mentees" and "For Mentors" pages, containing various guidelines on contributing to Jaeger and on the mentorship programs in general.
=> Add 'for mentees' and 'for mentors' pages

content/docs/next-release/spm.md
- Follow up task for https://github.com/jaegertracing/jaeger/pull/4452
- Updates the SPM documentation to reflect support for the spanmetrics connector.
- Provides link referencing documentation that provides guidance for migrating to the spanmetrics connector.
- Provides version compatibility guidance between jaeger and OTEL.
=> Update SPM docs to reflect support for spanmetrics connector

content/docs/1.29/operator.md, content/docs/1.30/operator.md, content/docs/1.31/operator.md, content/docs/1.32/operator.md, content/docs/1.33/operator.md, content/docs/1.34/operator.md, content/docs/1.35/operator.md, content/docs/1.36/operator.md, content/docs/1.37/operator.md, content/docs/1.38/operator.md, content/docs/1.39/operator.md, content/docs/1.40/operator.md, content/docs/1.41/operator.md, content/docs/1.42/operator.md, content/docs/1.43/operator.md, content/docs/1.44/operator.md, content/docs/1.45/operator.md, content/docs/1.46/operator.md, content/docs/next-release/operator.md
- fixes some typos in the jaeger operator installation guide
- `ClusterBindingRole` -> `ClusterRoleBinding`
=> Fix typo in Kubernetes installation docs

config.toml, content/docs/next-release/_index.md, content/docs/next-release/features.md, content/docs/next-release/getting-started.md, data/indexpage.yaml, themes/jaeger-docs/layouts/partials/home/features.html
- Remove some references to OpenTracing
- Provide links to HotROD blog
- Update wording on the home page and some intro pages
=> Refresh the docs with better language

themes/jaeger-docs/layouts/index.html, themes/jaeger-docs/layouts/partials/home/articles.html
- Resolves #677
- Fix Medium's post thumbnail
- Solution following: https://medium.com/@kartikyathakur/getting-those-thumbnails-from-medium-rss-feed-183f74aefa8c
- Manual test
=> Fix Medium's post thumbnail

content/docs/next-release/deployment.md
- Resolves #683
- Add Badger file permissions as non-root service link
- No
=> Add Badger file permissions as non-root service link

content/docs/next-release/sampling.md
Replaces https://github.com/jaegertracing/documentation/pull/676
=> List all storage backends are currently supported for adaptive sampling

content/docs/next-release/deployment.md
This PR lists the postgres-jaeger storage plugin that I maintain to the storage plugins list.
Adds a link to the storage plugin list.
It was visually checked.
=> Add jaeger-postgresql to storage plugins list

content/docs/next-release/deployment.md
- Updating documentation to reflect current state of jaeger-postgresql plugin. The plugin currently uses the remote storage interface.
-  Moves jaeger-postgresql to the remote storage backend plugin list.
- N/A
=> docs: moved jaeger-postgresql to remote plugin list

content/docs/1.48/monitoring.md, content/docs/1.49/monitoring.md, content/docs/1.50/monitoring.md, content/docs/1.51/monitoring.md, content/docs/1.52/monitoring.md, content/docs/1.53/monitoring.md, content/docs/1.54/monitoring.md, content/docs/1.55/monitoring.md, content/docs/1.56/monitoring.md, content/docs/next-release/monitoring.md
- Part of https://github.com/jaegertracing/jaeger/issues/5385
- Use OTEL env var that works with OTEL SDKs
- Update all docs starting from v1.48, when OTEL SDK were introduced
- Verified that starting all-in-one as below does not generate traces
```
$ OTEL_TRACES_SAMPLER=always_off go run -tags=ui ./cmd/all-in-one
```
=> Replace JAEGER_DISABLED with OTEL_TRACES_SAMPLER

.github/workflows/ci-test.yml
- Resolves https://github.com/jaegertracing/jaeger/issues/5271
-  Added the github actions file that check the PR is from main branch of fork and blocks it.
-  Will be tested
=> Github Action Added to Block PRs from fork/main branch

content/docs/1.44/troubleshooting.md, content/docs/1.45/troubleshooting.md, content/docs/1.46/troubleshooting.md, content/docs/1.47/troubleshooting.md, content/docs/1.48/troubleshooting.md, content/docs/1.49/troubleshooting.md, content/docs/1.50/troubleshooting.md, content/docs/1.51/troubleshooting.md, content/docs/1.52/troubleshooting.md, content/docs/1.53/troubleshooting.md, content/docs/1.54/troubleshooting.md, content/docs/1.55/troubleshooting.md, content/docs/1.56/troubleshooting.md, content/docs/1.57/troubleshooting.md, content/docs/next-release/troubleshooting.md
a typo in troubleshooting.MD
Surprisingly, the spellcheck didn't pick this one up, probably due to the Markdown hashtags being interpreted as a comment.
- [ X] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ X] I have signed all commits
=> Fix typo in OpenTelemetry

content/docs/next-release/_index.md, content/docs/next-release/apis.md, content/docs/next-release/deployment.md, content/docs/next-release/operator.md, scripts/cspell/project-words.txt, scripts/cspell/spellcheck.sh
- Part of https://github.com/jaegertracing/jaeger/issues/4647
- Replace `grpc-plugin` with `grpc` where applicable, remove otherwise.
- CI
=> Remove grpc-plugin storage type

content/docs/next-release/_index.md, content/docs/next-release/deployment.md, content/docs/next-release/features.md
- Relate https://github.com/jaegertracing/jaeger/issues/5439
- Remove ElasticSearch 5.x & 6.x documentation
- Manual
=> Remove: support ElasticSearch 5.x & 6.x

content/docs/1.58/spm.md, content/docs/next-release/spm.md
- Resolves https://github.com/jaegertracing/jaeger/issues/4736
=> Remove references to SpanMetrics Processor

themes/jaeger-docs/layouts/index.html, themes/jaeger-docs/layouts/partials/home/articles.html
- Resolves #710 
- Replaces #711
- Remove the use of JSON proxy server, read RSS as XML directly
- Change field names accordingly
- locally `make develop`
=> Fix RSS feed parsing

content/docs/1.59/deployment.md, content/docs/next-release/deployment.md
- We seem to be completely lacking documentation on using this image to create DB schema
- Add example of using the image
```
$ docker run --env CQLSH_HOST=192.168.68.82 jaegertracing/jaeger-cassandra-schema:1.59.0
Checking if Cassandra is up at 192.168.68.82:9042.
WARNING: cqlsh was built against 5.0-beta1, but this server is 3.11.17.  All features may not work!
WARN: DESCRIBE|DESC was moved to server side in Cassandra 4.0. As a consequence DESRIBE|DESC will not work in cqlsh '6.2.0' connected to Cassandra '3.11.17', the version that you are connected to. DESCRIBE does not exist server side prior Cassandra 4.0.
Cassandra connection established.
Cassandra version detected:
3
Generating the schema for the keyspace jaeger_v1_dc1 and datacenter dc1.
Using template file …
```
=> Mention jaeger-cassandra-schema Docker image

Makefile, content/docs/next-release-v2/_index.md
- Prepare for #731
- Add next-release-v2 directory for developing v2 documentation
- Do not include CLI flags into v2 during build
- `make develop`
=> Setup new structure for v2 docs

themes/jaeger-docs/assets/sass/article.sass, themes/jaeger-docs/assets/sass/pages.sass
This change will fix the spacing on all of the docs to make the screen real state better with less white space. It makes
a bigger difference in the v2 docs with the new TOC.
I did some testing on smaller screens as well.
Happy to get feedback.
=> fixing padding and spacing to get TOC to render right

themes/jaeger-docs/layouts/partials/docs/panel.html, themes/jaeger-docs/layouts/partials/navbar.html, themes/jaeger-docs/layouts/shortcodes/currentVersion.html, themes/jaeger-docs/layouts/shortcodes/dockerImages.html
- In v1.61.0 we stopped publishing shortcut Docker tags like `1` and `1.61`, and only publish fully qualified versions `1.61.0`
- But the docs were still referencing major/minor versions ([reported on Slack](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1727056265543819))
- Use fully qualified versions everywhere
- The docs URLs still use major.minor, so rename the variables to `$majorMinorVersion` to avoid confusion with the `currentVersion` shortcut
=> Use full versions in Docker commands

content/docs/next-release/apis.md, content/docs/next-release/architecture.md, content/docs/next-release/deployment.md, content/docs/next-release/external-guides.md, content/docs/next-release/faq.md, content/docs/next-release/getting-started.md, content/docs/next-release/monitoring.md, content/docs/next-release/operator.md, content/docs/next-release/performance-tuning.md, content/docs/next-release/sampling.md, content/docs/next-release/security.md, content/docs/next-release/troubleshooting.md, content/docs/next-release/windows.md
- Part of https://github.com/jaegertracing/jaeger/issues/4739
- Remove references to `jaeger-agent` everywhere except FAQ and Operator
- Operator page needs to be cleaned-up separately, perhaps it needs changes in the operator to support OTEL Collector as the agent
- CI
=> Remove references to jaeger-agent

themes/jaeger-docs/assets/sass/article.sass, themes/jaeger-docs/assets/sass/pages.sass, themes/jaeger-docs/assets/sass/toc.sass
- fixes #745
- fixed footer covering sidebar menu
- fixed the text covered by the scroll bar
- tested locally by running it using `make develop`
=> Fix footer covering sidebar menu

content/docs/next-release-v2/deployment.md, scripts/cspell/project-words.txt
Part of https://github.com/jaegertracing/documentation/issues/750
Adjusting command line and other components from v1 to v2.
=> Replace command line args in deployment doc

.github/workflows/ci-release.yml, Makefile, RELEASE.md, scripts/release.sh
- Part of #731
- Change release GH workflow from automatic to manual trigger
- Add support for dual v1/v2 release
```
$ DRY_RUN=true bash5 scripts/release.sh 1.64.0 2.0.0
+ safe_checkout_main
+ local checkoutBranch=main
+ [[ true = \t\r\u\e ]]
+ echo 'Skipping branch validation'
Skipping branch validation
+ return
+ for version in "${version_v1}" "${version_v2}"
++ echo 1.64.0
++ sed 's/\.[[:digit:]]$//'
+ versionMajorMinor=1.64
+ echo 'Creating new documentation for 1.64.0 (1.64)'
Creating new documentation for 1.64.0 (1.64)
+ var_suffix=
+ [[ 1.64 == 2* ]]
+ cp -r ./content/docs/next-release/ ./content/docs/1.64
++ grep -E 'versions *=' config.toml
+ versions='  versions = ["1.62","1.61","1.60","1.59","1.58","1.57","1.56","1.55","1.54","1.53","1.52"]'
+ [[   versions = …
```
=> Add support for v2 in the release workflow

content/docs/1.62/operator.md, content/docs/next-release/operator.md
- Resolves #768 
- To fix the URL in content/docs/1.62/operator.md, remove the extra .0 after {{< currentVersion >}} in the jaeger-operator.yaml URL. The {{< currentVersion >}} already includes the full version (major.minor.patch), so adding .0 results in an incorrect URL. This change resolves the 404 error.
=> Corrected the URL for jaegar-operator.yaml file 

README.md, content/roadmap.md, scripts/generate_roadmap.py
Add a Python script to generate a roadmap document from GitHub project board issues.
* Add `scripts/generate_roadmap.py` to fetch issues from the GitHub project board, extract the required information, and generate `content/roadmap.md`.
* Update `README.md` with instructions on how to run the script.
* Regenerate the Roadmap
Resolves #779
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/jaegertracing/documentation/pull/780?shareId=1ee122f8-54db-4ea2-9edd-5c0af96dc246).
=> Add script to generate roadmap from GitHub issues

Makefile, content/docs/next-release-v2/getting-started.md, content/download/_index.md, data/download.yaml, themes/basetheme/layouts/shortcodes/binaries.html, themes/basetheme/layouts/shortcodes/dockerImages.html, themes/jaeger-docs/layouts/index.html, themes/jaeger-docs/layouts/partials/navbar.html
- Link home page to v2 docs instead of v1
- Make the navbar Docs menu point to v2 instead of v1
- Update Download page to show v2 binaries
- Fix Makefile bug that was copying client* md files into v2 folders
- Remove 0.0.0.0 overrides from Getting Started as it was fixed for 2.1
- make develop
=> Make v2 docs the default

content/docs/next-release-v2/cassandra.md, content/docs/next-release-v2/configuration.md, content/docs/next-release-v2/deployment.md, content/docs/next-release-v2/elasticsearch.md, content/docs/next-release-v2/faq.md, content/docs/next-release-v2/kafka.md, content/docs/next-release-v2/opensearch.md, content/docs/next-release-v2/spm.md, content/docs/next-release-v2/windows.md, content/docs/next-release/spm.md, scripts/cspell/project-words.txt
- More improvements to the docs
- Address TODOs
=> Improve v2 docs

content/docs/next-release-v2/deployment.md, content/docs/next-release-v2/security.md, content/docs/next-release/security.md
- Resolves #525
- Resolves https://github.com/jaegertracing/jaeger/issues/1718
=> Add security page lost in v2 docs migration

content/docs/next-release/operator.md
- Resolves https://github.com/jaegertracing/documentation/issues/580
- Add a warning in lieu of more complex integration. In the v2 documentation we are always pointing the user to the operator's repo README.
=> Add warning about possible Operator version mismatch

content/docs/next-release-v2/apis.md, content/docs/next-release-v2/spm.md
- Resolves #495
- Only in v2 docs, remove remaining places that use `$` prefix
=> Remove dollar/prompt sign from code blocks

content/docs/next-release-v2/_index.md, content/docs/next-release-v2/getting-started.md
- For someone not familiar with distributed tracing we did not make it easy to learn the fundamentals.
- Pull the tutorials earlier in the intro.
=> Rearrange intro per tech writers recommendation

content/docs/next-release-v2/_index.md, content/news.md
- The Migration link under Introduction was looking out of context
- Add v2 blurb to the Introduction and link to Migration.
=> Emphasize v2 in the intro

content/docs/next-release-v2/frontend-ui.md, content/docs/next-release/frontend-ui.md
Documentation associated with https://github.com/jaegertracing/jaeger-ui/pull/2501
=> Update docs for link parameter formatting

scripts/release.sh
- Addresses https://github.com/jaegertracing/documentation/pull/840#pullrequestreview-2603959962
- Added a step to the release script to replace all instances of `https://github.com/jaegertracing/jaeger/tree/main` in `next-release/` and `next-release-v2/` with `https://github.com/jaegertracing/jaeger/tree/{version}`
- Ran the same sed command when performing the backfill in https://github.com/jaegertracing/documentation/pull/842
=> [release] Add step to release script for pinning links by jaeger version

content/docs/next-release-v2/apis.md, content/docs/next-release-v2/badger.md, content/docs/next-release-v2/cassandra.md, content/docs/next-release-v2/deployment.md, content/docs/next-release-v2/storage.md, content/docs/next-release/apis.md, content/docs/next-release/deployment.md, content/docs/next-release/operator.md
- Resolves #837
- Fixes references to old package locations from `plugin/storage` to `internal/storage/v1`
=> [chore] Fix references to `plugin/storage`

RELEASE.md
- Resolves #844 
- Part of https://github.com/jaegertracing/jaeger/issues/6688
- 
- 
=> Add markers to docs for checklist

content/docs/next-release-v2/configuration.md, content/docs/next-release-v2/deployment.md, content/docs/next-release-v2/faq.md
Resolves part of #117 
Add to FAQ
make develop
=> Add upgrade directions in FAQ

content/docs/2.6/apis.md, content/docs/2.6/storage.md
- Backports the new gRPC documentation to v2.6.0 since most of the changes were in that release
=> Backport gRPC documentation to v2.6

hugo.yaml
=> Drop obsolete GA UA ID from Hugo config

.htmltest.external.yml, .htmltest.old-versions.yml, Makefile, content/docs/2.0/architecture.md, content/docs/2.1/architecture.md, content/docs/2.2/architecture.md, content/docs/2.3/architecture.md, content/docs/2.4/architecture.md, content/docs/2.5/architecture.md, content/docs/2.6/architecture.md, content/docs/next-release-v2/architecture.md, content/docs/next-release/operator.md, content/get-involved.md, content/mentorship-for-mentees.md, data/refcache.json, hugo.yaml, themes/jaeger-docs/layouts/partials/docs/header.html, themes/jaeger-docs/layouts/partials/docs/panel.html, themes/jaeger-docs/layouts/partials/footer.html, themes/jaeger-docs/layouts/partials/javascript.html, themes/jaeger-docs/layouts/partials/meta.html
- Contributes to #889
- Resolves invalid links of the form `https://www.jaegertracing.io/docs/2.6/(cli|operator)/`
- Fixes `themes/jaeger-docs/layouts/partials/docs/header.html` so that it doesn't create invalid cross-version links
- Drops the now deprecated [canonifyURLs](https://gohugo.io/content-management/urls/#canonical-urls) Hugo config option, since it unnecessarily creates external links to intra-site targets, that should be encoded as simple paths
- Fixes other misc links and hash targets
- Adjusts some layouts so that local paths are used for intra-site links. When a full URL is required, we've added `data-proofer-ignore` so that the link checker doesn't need to be bothered with it.
=> Fix page cross-version links, drop canonifyURLs, and more

hugo.yaml
- Cleans up `hugo.yaml`.
- Mainly drops unused params config `navbar`
No change to the generated site files (neither for a dev nor a production build):
```console
$ make netlify-production-build
hugo --minify
...
Total in 13219 ms
$ (cd public && git diff)             
$ 
```
=> Hugo.yaml cleanup: drop unused navbar param

.github/workflows/ci-test.yml, netlify.toml, themes/jaeger-docs/layouts/partials/css.html
- Prep for #746
- Updates Hugo to v0.147.6 (in both files)
- Adjusts `themes/jaeger-docs/layouts/partials/css.html` so that we fingerprint the main `styles.css` file only in production
=> Update to Hugo v0.147.6, adjust theme css integrity

themes/jaeger-docs/layouts/partials/navbar.html
- Contributes to #746
- There are **no change to the generated production (i.e., minified) site files**
- Trims superfluous whitespace from `themes/jaeger-docs/layouts/partials/navbar.html`. This partial iterates over all docs, and for each iteration adds whitespace to the navbar. This creates files with _a lot_ of unnecessary blank lines, which makes it all the more challenging to diff the site-file changes necessary in preparation for the Docsy migration.
- In most cases, a Hugo template code statement ending in `}}` is replaced by `-}}`; a directive that will trim the excess whitespace following the directive when the page is generated.
=> Navbar partial whitespace cleanup

hugo.yaml, layouts/_partials/func/trim-lines.html, layouts/_partials/redirects/aliases.txt, layouts/_partials/redirects/pages.txt, layouts/_partials/redirects/redirect.txt, layouts/index.redirects
- Contributes to #913
- Adds layouts in support of the generation of page aliases as Netlify redirects. There are no such aliases fields in the current pages, but there will be once pages are moved. That is, there is no difference in the site page generation.
=> Add partials for redirect support of aliases etc

.cspell/project-words.txt, content/docs/_index.md, content/docs/v1/1.21/deployment/opentelemetry.md, content/docs/v1/1.63/client-libraries/_index.md, content/docs/v1/1.63/client-libraries/client-features.md, layouts/_partials/redirects.txt, layouts/index.redirects
- Contributes to:
- #928
- #929
- Fixes the following redirects:
- `/docs/operator` -> `/docs/1.69/operator`, rather than 2.6
- `/docs/client-features` -> `/docs/1.63/client-libraries/client-features/`
- `/docs/client-libraries` -> `/docs/1.63/client-libraries/`
- `/docs/opentelemetry` -> `/docs/1.21/deployment/opentelemetry/`
- Replaces hardcoded `$v2Pages` list by dynamically computed list of (recursive) pages under `v2/_dev`
- Adds code to prettify and sort redirect rules. This makes it easier to review for changes and duplicates
=> Fix operator 404, and more

.github/workflows/ci-test.yml, Makefile, README.md, netlify.toml, package.json, scripts/spellcheck.sh, themes/jaeger-docs/layouts/partials/navbar.html
- Fixes #921
- Makes the NPM scripts the primary method used to run build & CI commands. The makefile is still there, but plays a supporting role.
- Adds `hugo-extended` package as a means of getting the version of Hugo that the project needs. This greatly simplifies the ci-test.yml workflow
- FYI: this will also simplify the Docsy-based build, which will only require `WKSP=docsy`. The CI scripts remain the same.
=> [CI] Consolidate build-related files

content/docs/v2/2.3/getting-started.md, content/docs/v2/2.4/getting-started.md, content/docs/v2/2.5/getting-started.md, content/docs/v2/2.6/getting-started.md
The documentation says run `docker compose -f docker-compose-v2.yml up`, but now there is no `v2` in the compose file's name
Honestly, I did not run the tests :)
=> getting-started.md - the compose file is no longer called `-v2`

data/refcache.json
- Followup to #939
- Updates the refcache with new 1.70 & 2.7 external URLs
=> Update refcache following 2.7 release

package.json
- Updates all NPM packages (except for Bulma)
- In particular, updates Hugo to 0.150.1, and Docsy to `HEAD`
=> Update packages, Hugo to 0.150.1
