jaegertracing/documentation

- docs/features.md
- docs/index.md
- mkdocs.yml
> Add Features page

- docs/deployment.md
Related to https://github.com/jaegertracing/jaeger/issues/665
> Fix ES supported version

- docs/client_libraries.md
- docs/getting_started.md
- docs/index.md
Resolves https://github.com/jaegertracing/jaeger/issues/667
> Add section about client internals and samplers

- docs/monitoring.md
- mkdocs.yml
> Add a page describing metrics

- .travis.yml
- CONTRIBUTING.md
- Makefile
- README.md
> Add CONTRIBUTING.md

- docs/index.md
- requirements.txt
Broken link reported by @djalal in #13. Thanks for finding this!
> Fix broken envoy link

- README.md
Just fixed a dead link - https://www.jaegertracing.io
Signed-off-by: Saloni Garg salonigarg2310@gmail.com
> Dead Link Fixed

- README.md
- Add the license information to README
- Link to license
- Fixes #20 
Signed-off-by: Prakriti <prakritibansal98@gmail.com>
> Add the LICENSE information to README

- README.md
Shortcuts at the bottom of README.md file
Signed-off-by: shweta426060 <shwetasingh426060@gmail.com>
> Shortcuts at the bottom of README.md file

- docs/client_libraries.md
- docs/index.md
> Describe adaptive sampler

- Makefile
> Add check for Node version to Makefile

- content/docs/deployment.md
Add a note about `--query.base-path` and update the info on the UI config.
> Update UI config docs

- themes/jaeger-docs/layouts/partials/meta.html
Small metadata fix for Twitter Card compliance
> Fix Twitter Card metadata

- themes/jaeger-docs/layouts/partials/navbar.html
> Fix mismatched HTML tag in navbar

- themes/jaeger-docs/source/sass/article.sass
- themes/jaeger-docs/source/sass/toc.sass
> Adjust styling for inline code samples

- content/docs/deployment.md
README has info on purging old indexes and other implementation details.
Signed-off-by: Won Jun Jang <wjang@uber.com>
> Add link to ElasticSearch README

- config.toml
- themes/jaeger-docs/layouts/partials/home/hero.html
> Add link to April Newsletter

- content/docs/get-in-touch.md
- themes/jaeger-docs/layouts/partials/footer.html
Resolves #75 
Framework for #76
> Add Get-in-touch page

- content/docs/get-in-touch.md
- content/docs/report-security-issue.md
- themes/jaeger-docs/layouts/partials/footer.html
> Add 'Report Security Issue' page

- content/docs/client-libraries.md
Since the tutorial is merged now, we should update this document as well.
> Added notice about C# tutorial

- data/clients.yaml
The new v0.0.10 release of the C# client now supports almost the same features as Java.
I couldn't run this locally so I couldn't test it. Hope it's fine though.
(resolves https://github.com/jaegertracing/jaeger-client-csharp/issues/51)
> Update C# client features

- data/clients.yaml
Signed-off-by: Chandresh Pancholi <chandreshpancholi007@gmail.com>
> Remove reference to JAEGER_DISABLE_GLOBAL_TRACER

- content/docs/getting-started.md
Signed-off-by: chandresh-pancholi <chandreshpancholi007@gmail.com>
- Resolves #60 
- Replacing traditional way of running hotrod example to docker way
> Add instructions to run HotROD from Docker image

- content/docs/client-libraries.md
> Fix broken link

- config.toml
> Update newsletter link for June

- Makefile
- netlify.toml
- themes/jaeger-docs/layouts/partials/css.html
Something went awry with the site deploy. This PR seeks to fix that.
> Fix website CSS

- config.toml
- Resolves #112 (hopefully)
- Added `www` to the `baseURL`
> Fix baseURL to include www

- content/docs/sampling.md
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Fix typo in sampling documentation JSON example

- content/docs/download.md
- themes/jaeger-docs/layouts/partials/home/hero.html
Signed-off-by: Prakriti <prakritibansal98@gmail.com>
- resolves #114 
- Add download docs 
- Reinstate download button
> Reinstate Download button

- themes/jaeger-docs/layouts/partials/navbar.html
> Remove docs with "hasparent: true" from docs menu

- config.toml
> October 2018 Newsletter

- README.md
> Add instructions how to add a new version

- content/docs/1.6/_index.md
- content/docs/1.7/_index.md
- content/docs/1.8/_index.md
See https://github.com/jaegertracing/documentation/pull/167/files/b8aa78c731957219de2ae0526f6977003c216c11#diff-bbd6155604283711b0724bbf97a5b18c
> Change we to uber

- content/docs/1.6/deployment.md
- content/docs/1.7/deployment.md
- content/docs/1.8/deployment.md
> Clarify archived traces

- README.md
- config.toml
> Update instructions on making a new release

- DCO
Signed-off-by: Yevgeny Petukhov <petukhov.yevgeny@gmail.com>
> DCO is added

- data/clients.yaml
Pending https://github.com/jaegertracing/jaeger-client-node/pull/311
> Env variables for nodejs are updated

- data/clients.yaml
* Add descriptions to all env vars
* Change the order to keep related vars close to each other
> Document and re-arrange env vars

- Makefile
- config.toml
- netlify.toml
- themes/jaeger-docs/layouts/partials/navbar.html
> Display next-release in Versions in dev/preview

- config.toml
- content/docs/1.9/_index.md
- content/docs/1.9/architecture.md
- content/docs/1.9/client-features.md
- content/docs/1.9/client-libraries.md
- content/docs/1.9/deployment.md
- content/docs/1.9/features.md
- content/docs/1.9/frontend-ui.md
- content/docs/1.9/getting-started.md
- content/docs/1.9/monitoring.md
- content/docs/1.9/sampling.md
- content/docs/1.9/troubleshooting.md
> Release 1.9 docs

- content/docs/1.9/troubleshooting.md
- content/docs/next-release/troubleshooting.md
> Added link from the troubleshooting page to blog post

- content/docs/next-release/deployment.md
- Documentation to go along with https://github.com/jaegertracing/jaeger/pull/1329
> Add description of gRPC load-balancing and resolver options

- content/docs/1.9/deployment.md
- content/docs/next-release/deployment.md
Signed-off-by: Annanay <annanay.a@media.net>
- Adds a quick deployment example of jaeger-query without having to use `--help` option
> Add basic docker deployment example for jaeger-query 

- config.toml
- content/docs/1.10/_index.md
- content/docs/1.10/architecture.md
- content/docs/1.10/client-features.md
- content/docs/1.10/client-libraries.md
- content/docs/1.10/deployment.md
- content/docs/1.10/features.md
- content/docs/1.10/frontend-ui.md
- content/docs/1.10/getting-started.md
- content/docs/1.10/monitoring.md
- content/docs/1.10/sampling.md
- content/docs/1.10/troubleshooting.md
> Release 1.10.0

- themes/jaeger-docs/layouts/shortcodes/binaries.html
> Temporary patch to fix download links

- themes/jaeger-docs/layouts/partials/footer.html
Social icons done gone missing, same fix as for Download links
Ref: #229
> Restore social icons in the footer

- themes/jaeger-docs/layouts/partials/home/cncf.html
This PR provides a more accurate description of Jaeger's status in the CNCF
> Update CNCF project status

- content/docs/1.10/deployment.md
- content/docs/1.11/deployment.md
- content/docs/1.8/deployment.md
- content/docs/1.9/deployment.md
- content/docs/next-release/deployment.md
Updates https://github.com/jaegertracing/jaeger/issues/1528
> Add badger and gprc plugin

- content/docs/1.12/deployment.md
- content/docs/next-release/deployment.md
Resolves https://github.com/jaegertracing/jaeger/issues/1543
Credit to @srispl
> Fix Badger sample command

- content/docs/1.12/deployment.md
- content/docs/next-release/deployment.md
> Explain agent's UDP ports

- README.md
- themes/jaeger-docs/assets/sass/article.sass
- themes/jaeger-docs/layouts/partials/admonition.html
- themes/jaeger-docs/layouts/shortcodes/danger.html
- themes/jaeger-docs/layouts/shortcodes/info.html
- themes/jaeger-docs/layouts/shortcodes/requirement.html
- themes/jaeger-docs/layouts/shortcodes/success.html
- themes/jaeger-docs/layouts/shortcodes/warning.html
This PR adds five admonition blocks:
* `info`
* `requirement`
* `danger`
* `warning`
* `success`
> Add admonition shortcodes

- content/docs/1.13/troubleshooting.md
- content/docs/next-release/troubleshooting.md
> Added content from blog post to troubleshooting page

- content/docs/1.13/operator.md
- content/docs/next-release/operator.md
Add index cleaner job section related to https://github.com/jaegertracing/jaeger-operator/commit/0d6bd5fbd5b5ecb6f8138d7a5222689962dbd1aa#diff-7bd4a925c695c2eb0eced3872b9b965f
OAuth Proxy options associated with https://github.com/jaegertracing/jaeger-operator/commit/b2dbd01380216eb243c1f8f708ca8ddff48c6b4f#diff-7bd4a925c695c2eb0eced3872b9b965f
Security Context and Service Account with https://github.com/jaegertracing/jaeger-operator/commit/4005a6b50f1fb1e3fa55742658184c9835ea4932#diff-7bd4a925c695c2eb0eced3872b9b965f
> Update jaeger operator documentation to include most recent changes to its README

- content/docs/1.13/performance-tuning.md
- content/docs/next-release/performance-tuning.md
> Added performance tuning guide

- content/docs/1.13/troubleshooting.md
- content/docs/next-release/troubleshooting.md
> Fix capitalization and minor typos

- content/docs/1.13/operator.md
- content/docs/next-release/operator.md
Fixes https://github.com/jaegertracing/documentation/issues/259
Will apply changes to `next-release` once approved.
Documenting the use of labels in jaeger-operator CR.
Added info about configuring labels, and extended the existing CR example.
> Add docs for labels

- content/docs/1.13/_index.md
- content/docs/1.13/architecture.md
- content/docs/1.13/cli.md
- content/docs/1.13/client-libraries.md
- content/docs/1.13/deployment.md
- content/docs/1.13/faq.md
- content/docs/1.13/features.md
- content/docs/1.13/frontend-ui.md
- content/docs/1.13/operator.md
- content/docs/1.13/sampling.md
- content/docs/next-release/_index.md
- content/docs/next-release/architecture.md
- content/docs/next-release/client-libraries.md
- content/docs/next-release/deployment.md
- content/docs/next-release/faq.md
- content/docs/next-release/features.md
- content/docs/next-release/frontend-ui.md
- content/docs/next-release/operator.md
- content/docs/next-release/sampling.md
- themes/jaeger-docs/layouts/partials/docs/header.html
- themes/jaeger-docs/layouts/partials/docs/panel.html
* Move some of the top-level pages into sub-pages
* Add summary of sub-pages at the top of the parent page (because left side menu is not  shown on mobile)
> Reorganize left side menu

- themes/jaeger-docs/layouts/index.html
- themes/jaeger-docs/layouts/partials/home/hero.html
This PR fixes a build issue involved with JSON parsing. It turns out that this part of the build isn't even currently used on the site, so it's safe to remove.
> Remove newsletter logic from build

- content/docs/1.13/client-features.md
- content/docs/1.13/client-libraries.md
- content/docs/1.13/getting-started.md
- content/docs/next-release/client-features.md
- content/docs/next-release/client-libraries.md
- content/docs/next-release/getting-started.md
This makes the page titles consistently capitalized.
cc @jpkrohling
> Fix title capitalization

- content/docs/next-release/operator.md
Documentation for jaegertracing/jaeger-operator#573
> Added documentation about htpasswd auth for the Operator

- content/docs/1.12/deployment.md
- content/docs/next-release/deployment.md
> Clarify that agent tags are not supported for tchannel

- content/docs/next-release/operator.md
> Document spark dependencies in operator

- data/clients.yaml
- Updates the matrix according to currently supported environment variables. 
- `jaeger-client-python`
- https://github.com/jaegertracing/jaeger-client-python/blame/master/jaeger_client/config.py#L305
- https://github.com/jaegertracing/jaeger-client-python/blame/master/jaeger_client/config.py#L290
- https://github.com/jaegertracing/jaeger-client-python/blame/master/jaeger_client/config.py#L277
- `jaeger-client-go`
- https://github.com/jaegertracing/jaeger-client-go/blame/master/config/config_env.go#L45-L47
> Update tracer config environment variables section

- content/docs/1.10/_index.md
- content/docs/1.11/_index.md
- content/docs/1.12/_index.md
- content/docs/1.13/_index.md
- content/docs/1.14/_index.md
- content/docs/1.6/_index.md
- content/docs/1.7/_index.md
- content/docs/1.8/_index.md
- content/docs/1.9/_index.md
- content/docs/next-release/_index.md
- Closes https://github.com/jaegertracing/documentation/issues/168
- rearranged contact info in all past versions of docs as well as `next-release`
> Rearranged contact info for all versions of jaeger docs

- content/docs/1.14/deployment.md
- content/docs/next-release/deployment.md
Resolves https://github.com/jaegertracing/jaeger/pull/1866
https://discuss.elastic.co/t/elasticsearch-7-mappping-on-elasticsearch-6/203681/6
> Correct Elasticsearch data migration

- content/docs/1.13/operator.md
- content/docs/1.14/operator.md
- content/docs/next-release/operator.md
Resolves #299 
Added note about jaeger sidecar agent hostname to v1.13, v.14 and next release
> Add note about Jaeger Agent hostname for sidecar deployments

- content/docs/next-release/operator.md
> Improve operator Elasticsearch docs

- content/docs/1.13/operator.md
- content/docs/1.14/operator.md
- content/docs/1.15/operator.md
- content/docs/next-release/operator.md
> Fix link to Jaeger operator CRD

- themes/jaeger-docs/layouts/shortcodes/cli/tools-list.html
Resolves  #327
cc @pavolloffay
> Remove code formatting from links

- content/docs/1.16/operator.md
- content/docs/next-release/operator.md
> Mention that ES operator was used in external ES example

- content/docs/1.12/architecture.md
- content/docs/1.13/architecture.md
- content/docs/1.14/architecture.md
- content/docs/1.15/architecture.md
- content/docs/1.16/architecture.md
- content/docs/next-release/architecture.md
- quick typo fix
- adds missed word in documentation
> fix missed word typo on components architecture

- content/docs/next-release/architecture.md
- data/definitions.yaml
> Clarify sampling

- content/docs/1.12/deployment.md
- content/docs/1.13/deployment.md
- content/docs/1.14/deployment.md
- content/docs/1.15/deployment.md
- content/docs/1.16/deployment.md
- content/docs/next-release/deployment.md
Fixed typo `GRPC_STORAGE_PLUGIN_CONFIGURATION_FINE` => `GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE`
> Fixed fine => file typo

- content/docs/1.16/operator.md
- content/docs/next-release/operator.md
Related to https://github.com/jaegertracing/jaeger-operator/issues/745#issuecomment-57931929
> Spark in operator, document memory resources

- content/docs/next-release/operator.md
Related to https://github.com/jaegertracing/jaeger-operator/pull/897 and https://github.com/jaegertracing/jaeger-operator/pull/903/
> Kubernetes agent injection on namespaces

- content/docs/next-release/frontend-ui.md
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
- This PR document  jaeger-ui feature introduced in PR: https://github.com/jaegertracing/jaeger-ui/pull/480
- Added trace as a link pattern type, and describe exposed fields for templating the link/text.
> Add traces link patterns documentation

- themes/jaeger-docs/assets/js/app.js
Fixes #352
Compare the following two links to see the difference:
https://deploy-preview-366--jaegertracing.netlify.com/docs/1.16/#quick-start
https://jaegertracing.io/docs/1.16/#quick-start
> Fix anchor scroll issue

- themes/jaeger-docs/layouts/partials/navbar.html
This PR fixes an issue where documentation links are broken in the mobile view on some pages.
> Fix navigation issue

- content/docs/1.17/deployment.md
- content/docs/next-release/deployment.md
> Document Elasticsearch rollover

- content/docs/1.17/operator.md
- Fix deadlockInterval for ingester.
- Add index-prefix option for es storage
> Improve operator documentation

- content/docs/1.17/operator.md
- content/docs/next-release/operator.md
- Documenting how to configure the Jaeger Operator
> Added documentation about how to configure the operator

- content/docs/next-release/deployment.md
Related to https://github.com/jaegertracing/jaeger/issues/2105
> Remove tchannel port from collector

- data/clients.yaml
Related to https://github.com/jaegertracing/jaeger-client-java/pull/694
> Support w3c tracecontext

- content/docs/1.17/operator.md
- content/docs/next-release/operator.md
- to be consistent with the create commands
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> Fix doc: add namespace to the delete commands

- content/docs/1.16/deployment.md
- content/docs/1.17/deployment.md
- content/docs/next-release/deployment.md
- Fix #392 
- Set right variable name
> Fix Kafka brokers environement variable

- content/docs/1.17/_index.md
- content/docs/next-release/_index.md
- C# was missing on the introduction page
- Linked C# client
> Added C# to client list

- themes/jaeger-docs/assets/sass/footer.sass
- themes/jaeger-docs/layouts/partials/footer.html
This PR adds copyright text required by the Linux Foundation.
> Add copyright footer

- content/docs/1.17/monitoring.md
- content/docs/next-release/monitoring.md
> Document self-tracing and how to disable it

- content/docs/1.17/monitoring.md
- content/docs/next-release/monitoring.md
> Document jaeger mixin for monitoring

- content/docs/1.18/deployment.md
- content/docs/1.18/security.md
- content/docs/next-release/deployment.md
- content/docs/next-release/security.md
- themes/jaeger-docs/layouts/shortcodes/featuresTable.html
The situation is not ideal, but it's better to be transparent and ask for help.
> Document existing security mechanisms

- content/docs/1.18/operator.md
- content/docs/next-release/operator.md
Add documentation for ingester auto-scaling.
Similar docs to those provided for collector auto-scaling.
> Add docs for autoscaling ingester

- content/docs/1.18/operator.md
- content/docs/next-release/operator.md
> Fix rollover TTL value

- content/docs/next-release/_index.md
- content/docs/next-release/features.md
- Resolves #424
- Add a detailed document to talk about jaeger topology.
> Add a topic talk about jaeger topology

- content/docs/1.19/deployment.md
- content/docs/next-release/deployment.md
https://github.com/jaegertracing/jaeger/issues/1459#issuecomment-682284426
> Explain clock skew adjustment and flag

- content/docs/1.19/_index.md
- content/docs/next-release/_index.md
- Fix invalid link in the Introduction page to the Istio's Jaeger page.
- Fix URL
> Fix invalid Istio docs URL

- content/docs/1.18/opentelemetry.md
- content/docs/1.19/opentelemetry.md
- content/docs/next-release/opentelemetry.md
> Fix link to deployment page

- content/docs/1.19/operator.md
- content/docs/next-release/operator.md
Resolves https://github.com/jaegertracing/jaeger-operator/issues/1187
Once this is approved I will copy it to the older releases.
> Document how to use ES ILM with operator

- content/docs/1.10/client-libraries.md
- content/docs/1.11/client-libraries.md
- content/docs/1.12/client-libraries.md
- content/docs/1.13/client-libraries.md
- content/docs/1.14/client-libraries.md
- content/docs/1.15/client-libraries.md
- content/docs/1.16/client-libraries.md
- content/docs/1.17/client-libraries.md
- content/docs/1.18/client-libraries.md
- content/docs/1.19/client-libraries.md
- content/docs/1.20/client-libraries.md
- content/docs/1.6/client-libraries.md
- content/docs/1.7/client-libraries.md
- content/docs/1.8/client-libraries.md
- content/docs/1.9/client-libraries.md
- content/docs/next-release/client-libraries.md
> Clarify propagation format for flags

- themes/jaeger-docs/layouts/partials/docs/header.html
- themes/jaeger-docs/layouts/partials/meta.html
Signed-off-by: Celeste Horgan <celeste@cncf.io>
Fixes links mentioned in #437.
> Fix broken links

- config.toml
- content/get-in-touch.md
Signed-off-by: Yakam Jennifer <yakamjennifer@gmail.com>
Which problem is this PR solving?
The PR adds the Jaeger project bi-weekly calendar into the website.
Short description of the changes
It helps to bring visibility to our bi-weekly meeting and resolves #383
> Integrated the jaeger project bi-weekly calendar into the website #383

- content/docs/next-release/cli.md
Signed-off-by: Chen Zhengwei <chenzhengwei@inspur.com>
- https://github.com/jaegertracing/jaeger/issues/2361
- Add status command in cli.md
> Add status command in cli.md

- content/roadmap.md
Signed-off-by: Chen Zhengwei <chenzhengwei@inspur.com>
- Fix OpenTelemetry collector link
> Fix OpenTelemetry collector link

- content/docs/1.21/operator.md
> Fix operator storage identation

- content/docs/1.21/_index.md
- content/docs/1.21/getting-started.md
- content/docs/next-release/_index.md
- content/docs/next-release/getting-started.md
These seem pretty good and focused on Jaeger.
> Add cloudnative101.dev tutorials

- .gitignore
- content/docs/next-release/deployment.md
Signed-off-by: santosh <bsantosh@thoughtworks.com>
- Resolves #471 
- Adds documentation for enabling usage of ILM in elasticsearch for managing jaeger indices.
> #471 - Add ILM documentation

- content/docs/1.18/opentelemetry.md
- content/docs/1.19/opentelemetry.md
- content/docs/1.20/opentelemetry.md
- content/docs/1.21/opentelemetry.md
- content/docs/next-release/opentelemetry.md
> Fixed broken link in opentelemetry.md

- content/docs/1.22/deployment.md
- content/docs/next-release/deployment.md
Signed-off-by: Ashmita Bohara <ashmita.bohara152@gmail.com>
Add links of quay images for jaeger components.
> Update documentation with quay images

- .github/ISSUE_TEMPLATE.md
- config.toml
- content/docs/1.22/_index.md
- content/docs/next-release/_index.md
- content/get-in-touch.md
- content/report-security-issue.md
- themes/jaeger-docs/layouts/partials/footer.html
> Replace Gitter with Slack

- content/docs/1.10/_index.md
- content/docs/1.11/_index.md
- content/docs/1.12/_index.md
- content/docs/1.13/_index.md
- content/docs/1.14/_index.md
- content/docs/1.15/_index.md
- content/docs/1.16/_index.md
- content/docs/1.17/_index.md
- content/docs/1.18/_index.md
- content/docs/1.19/_index.md
- content/docs/1.20/_index.md
- content/docs/1.21/_index.md
- content/docs/1.6/_index.md
- content/docs/1.7/_index.md
- content/docs/1.8/_index.md
- content/docs/1.9/_index.md
Signed-off-by: lastchiliarch <lastchiliarch@gmail.com>
-  Update Jaeger community support URL, #478 
-  Update Jaeger community support UR
> Update Jaeger community support URL #478

- content/docs/1.17/operator.md
- content/docs/1.18/operator.md
- content/docs/1.19/operator.md
- content/docs/1.20/operator.md
- content/docs/1.21/operator.md
- content/docs/1.22/operator.md
- content/docs/next-release/operator.md
WATCH_NAMESPACE was incorrectly pluralized in the docs.
> Fixed WATCH_NAMESPACE env var for jaeger operator

- content/docs/1.13/operator.md
- content/docs/1.14/operator.md
- content/docs/1.15/operator.md
- content/docs/1.16/operator.md
- content/docs/1.17/operator.md
- content/docs/1.18/operator.md
- content/docs/1.19/operator.md
- content/docs/1.20/operator.md
- content/docs/1.21/operator.md
- content/docs/1.22/operator.md
- content/docs/next-release/operator.md
`//` is not valid comment in yaml, replace with `#` to make it easy to copy paste
> fix: Use valid yaml comments in examples

- content/roadmap.md
Fixing up my botched PR #498 which will be closed in favor of this PR. Several items in the Ideation list will be presented in the coming weeks for discussion in the community calls including POCs. 
Signed-off-by: Jonah Kowall <jkowall@kowall.net>
> Updates per discussion in Roadmap session

- content/docs/1.22/getting-started.md
- content/docs/next-release/getting-started.md
> Remove explicit Go version, point to repo instead

- .github/workflows/ci-release.yml
- travis/release.sh
CI opens PR with new version of the docs
> Fix automated release process

- content/docs/next-release/operator.md
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
> Add gprc-plugin operator docs

- RELEASE.md
- Make it clear that the tagging should be performed from master, not a feature branch.
- Provide links to the Actions and PR tabs for quicker navigation to perform next steps.
> Add release notes suggestions

- content/docs/1.28/operator.md
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
> Use operator pined url version for install instructions

- content/docs/1.29/operator.md
- content/docs/next-release/operator.md
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
-  Due some changes on the generated manifest and how Jaeger Operator is released we need to change the documentation to align it with the current release manifest.
> Update jaeger operator documentation

- content/_client_libs/client-libraries.md
- content/docs/1.29/deployment.md
- content/docs/1.29/getting-started.md
- content/docs/next-release/deployment.md
- content/docs/next-release/getting-started.md
- content/docs/next-release/operator.md
> Add all-in-one to deployment docs

- content/docs/1.29/external-guides.md
- content/docs/1.29/performance-tuning.md
- content/docs/next-release/external-guides.md
- content/docs/next-release/performance-tuning.md
- themes/jaeger-docs/layouts/partials/navbar.html
> Add a page with external guides

- content/docs/1.29/external-guides.md
- content/docs/next-release/external-guides.md
- Fixes typo discovered in code review: https://github.com/jaegertracing/documentation/pull/544#discussion_r777897693
> Fix typo in Troubleshooting header

- content/docs/next-release/apis.md
Follow-up to https://github.com/jaegertracing/jaeger/issues/3417
> Improve APIs page, mention gRPC reflection

- netlify.toml
This is not the latest version, but that's what `brew upgrade hugo` installed, so seems a good state to move towards.
> Upgrade hugo to 0.92

- content/docs/1.31/operator.md
- content/docs/1.32/operator.md
- content/docs/next-release/operator.md
Closes #560
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
---
cc @pavolloffay @rubenvp8510
> mention cert-manager requirement for operator v1.31 and higher

- content/docs/next-release/_index.md
- content/docs/next-release/apis.md
- content/docs/next-release/deployment.md
- content/docs/next-release/features.md
- content/docs/next-release/frontend-ui.md
- content/docs/next-release/getting-started.md
- content/docs/next-release/operator.md
- content/docs/next-release/spm.md
- Context: https://github.com/jaegertracing/jaeger-ui/pull/916#discussion_r835734788
- `s/Aggregated Trace Metrics/Service Performance Monitoring/g`
- `s/ATM/SPM/g`
- `s/atm/spm/g`
> ATM to SPM

- content/docs/1.30/deployment.md
- content/docs/1.31/deployment.md
- content/docs/1.32/deployment.md
- content/docs/1.33/deployment.md
- content/docs/next-release/deployment.md
https://github.com/jaegertracing/jaeger/issues/3377
> Mention gRPC remote storage option

- content/docs/next-release/deployment.md
Signed-off-by: Rajakavitha Kodhandapani <krajakavitha@gmail.com>
Readers may need more information about how to send data.
Added a link to the documentation for more information.
> Added a link to the documentation 

- content/docs/next-release/_index.md
- content/docs/next-release/deployment.md
- content/docs/next-release/features.md
Promscale is known to Jaeger complaint[1] since v0.16.0[2].
[1] https://github.com/timescale/promscale/actions/runs/3293909868/jobs/5430887629#step:6:292-354 
[2] https://github.com/timescale/promscale/releases/tag/0.16.0
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
- 
-
> Mention `PostgreSQL with Promscale` as Jaeger span storage

- content/download/_index.md
Now that 1.40.0 has been released this note is no longer valid
> Remove note

- content/docs/next-release/_index.md
- content/docs/next-release/deployment.md
- content/docs/next-release/features.md
[Promscale has been discontinued](https://github.com/timescale/promscale/issues/1836#top)
> Remove Promscale from docs

- content/docs/next-release/frontend-ui.md
Updating the documentation for the linkPatterns change done in jaeger ui in PR https://github.com/jaegertracing/jaeger-ui/pull/1178
> Add documentation for jaeger ui PR#1178

- .github/workflows/ci-test.yml
- Makefile
* Add test workflow that runs the build and checks local links
> Add test workflow

- content/docs/next-release/deployment.md
- content/docs/next-release/faq.md
- content/docs/next-release/performance-tuning.md
- https://github.com/jaegertracing/documentation/issues/608
- Add warnings that Agent is no longer needed
> De-emphasize jaeger-agent

- content/docs/next-release/features.md
- content/docs/next-release/frontend-ui.md
- content/docs/next-release/spm.md
Improved docs for supported backends, and removed monitor tab and SPM experimental mentions.
> Improved docs for supported backends, removed monitor tab and SPM experimental mentions.

- content/docs/1.43/deployment.md
- content/docs/next-release/deployment.md
- https://github.com/jaegertracing/jaeger/issues/4284
- Adds a reference link for Cassandra schema management.
> Add reference link for Cassandra schema management

- content/roadmap.md
Updating a few items in the roadmap per discussion. This includes removing a few completed items and adding ClickHouse support.
> Updated roadmap with a few removals and an addition

- content/docs/next-release/spm.md
Fixes: #624
- Add a troubleshooting note to the SPM docs for how to handle 403 errors.
> Add troubleshooting guide for 403 error

- content/docs/next-release/apis.md
- content/docs/next-release/deployment.md
- content/docs/next-release/faq.md
- content/docs/next-release/getting-started.md
Fixes #612
Naming Convention Of:
- apis.md
- deployment.md
- faq.md
- getting-started.md
made consistent with the guidelines given in the issue
> Consistent Naming For Jaeger Components

- content/docs/1.48/getting-started.md
- content/docs/next-release/getting-started.md
- Address https://github.com/jaegertracing/documentation/pull/648/files#r1302207961
- Fix Docker commands
- Ran locally
> Fix instructions for running HotROD

- data/indexpage.yaml
- themes/jaeger-docs/layouts/partials/footer.html
- update some material-ui icons to better match the features being called out
- fix the size of Slack icon in the footer
> Use better icons on home page and fix Slack icon

- .github/workflows/ci-test.yml
- Link checking currently fails, will open another issue to look into it.
- Only do a build, don't check links
> Disable links checking

- content/mentorship-for-mentees.md
- content/mentorship.md
Based on some of the questions we are getting from our new Mentees we wanted to add some additional pointers and clarification ot make it easier for them to get started. 
Added link for the current ongoing LFX mentorship. 
Tested new page locally.
> Adding some additional clarification for mentees.

- content/mentorship.md
- added LFX mentorship march-may 2024 (Term 1) mentees
> Add LFX mentorship march-may 2024 (Term 1) mentees

- content/mentorship.md
- Added GSoC 2024 Application Dates
> Add GSoC 2024 Application Dates

- themes/jaeger-docs/layouts/_default/single.html
- Resolves #674
- Fix single page header anchor
- Manual test
> Fix: Single page header anchor

- content/docs/next-release/_index.md
- content/docs/next-release/apis.md
- content/docs/next-release/architecture.md
- content/docs/next-release/cli.md
- content/docs/next-release/deployment.md
- content/docs/next-release/faq.md
- content/docs/next-release/features.md
Solving issue:-
[fix spelling issues #701]
Grammatical errors have been corrected in the docs next-release/*.md
replaces closed PR #716
> Fix grammar errors

- content/download/_index.md
> Mention v2 artifacts and docs

- content/docs/next-release-v2/spm.md
- scripts/cspell/project-words.txt
- Resolves #772
- Update diagram, remove implication that OTEL Collector is needed
- Update the docs for v2
- Add configuration references / samples
> Update SPM docs

- content/docs/1.40/operator.md
- content/docs/1.41/operator.md
- content/docs/1.42/operator.md
- content/docs/1.43/operator.md
- content/docs/1.44/operator.md
- content/docs/1.45/operator.md
- content/docs/1.46/operator.md
- content/docs/1.47/operator.md
- content/docs/1.48/operator.md
- content/docs/1.49/operator.md
- content/docs/1.50/operator.md
- content/docs/1.51/operator.md
- content/docs/1.52/operator.md
- content/docs/1.53/operator.md
- content/docs/1.54/operator.md
- content/docs/1.55/operator.md
- content/docs/1.56/operator.md
- content/docs/1.57/operator.md
- content/docs/1.58/operator.md
- content/docs/1.59/operator.md
- content/docs/1.60/operator.md
- content/docs/1.61/operator.md
- content/docs/1.62/operator.md
- content/docs/1.63/operator.md
- content/docs/next-release/operator.md
- scripts/cspell/project-names.txt
- scripts/cspell/project-words.txt
- Resolves #701
- Final clean-up
> Clean-up dictionaries

- content/docs/next-release-v2/_index.md
- content/docs/next-release-v2/architecture.md
- content/docs/next-release-v2/frontend-ui.md
- content/docs/next-release-v2/spm.md
- content/docs/next-release-v2/terminology.md
- content/docs/next-release/_index.md
- content/docs/next-release/architecture.md
- content/docs/next-release/frontend-ui.md
- content/docs/next-release/spm.md
- Resolves #666
- Surround inline images with a hyperlink to the same image
> Make all illustrations popup on click

- content/docs/next-release-v2/storage.md
> Add explanation of Archive storage

- content/docs/next-release-v2/windows.md
> Update Windows docs

- content/docs/next-release-v2/cassandra.md
- content/docs/next-release-v2/deployment.md
- Part of https://github.com/jaegertracing/jaeger/issues/5797
- Show example of schema auto-gen and config
> Mention Cassandra schema auto-generation

- content/docs/2.1/monitoring.md
- content/docs/next-release-v2/monitoring.md
- Resolves #394 again (regression in v2 docs)
- Explain `OTEL_TRACES_SAMPLER=always_off` environment variable.
> Explain how to disable self-tracing

- themes/basetheme/layouts/shortcodes/binaries.html
> Fix Download links for v2 artifacts

- content/docs/next-release-v2/architecture.md
- content/docs/next-release-v2/deployment.md
- content/docs/next-release-v2/getting-started.md
- https://github.com/orgs/jaegertracing/discussions/6623
> Add example of passing a config file

- themes/jaeger-docs/layouts/index.html
- themes/jaeger-docs/layouts/partials/home/thanks.html
Continues : https://github.com/jaegertracing/jaeger/issues/6577
Add section to homepage and add text to section thanking our sponsors. 
make spellcheck
make develop
Test page
> Add section for thanking sponsors to homepage

- content/docs/2.0/kubernetes.md
- content/docs/2.1/kubernetes.md
- content/docs/2.2/kubernetes.md
- content/docs/2.3/kubernetes.md
- content/docs/next-release-v2/kubernetes.md
- Instead of linking to issues link to READMEs of what's already available
> Update v2 Kubernetes docs

- .github/workflows/ci-test.yml
- netlify.toml
- themes/jaeger-docs/layouts/index.html
Resolves #850 
- added try functionality as new version of hugo
- 
> Upgrade Hugo version to v0.143.1

- content/docs/next-release-v2/configuration.md
- https://github.com/orgs/jaegertracing/discussions/6778#discussioncomment-12340772
> Explain use of environment variables

- content/docs/2.0/deployment.md
- content/docs/2.1/deployment.md
- content/docs/2.2/deployment.md
- content/docs/2.3/deployment.md
- content/docs/2.4/deployment.md
- content/docs/next-release-v2/deployment.md
Resolves https://github.com/jaegertracing/jaeger/issues/6929
> Fix incorrect config option name

- themes/jaeger-docs/assets/sass/toc.sass
- Resolves #744 
- Fix Right Sidebar,made it **extend through the suitable space**.....provided room for the content **to expand in width as well**
****
- Locally tested with `make develop`
> Make right sidebar taller

- content/docs/2.5/elasticsearch.md
- content/docs/next-release-v2/elasticsearch.md
> Update elasticsearch config link

- content/docs/next-release-v2/architecture.md
- content/docs/next-release-v2/configuration.md
- Resolves https://github.com/jaegertracing/jaeger/issues/6683
- Closes #870
> Add references to configs

- content/docs/next-release-v2/architecture.md
- scripts/cspell/project-words.txt
- Mention recently added pprof extension and Filter Processor
> Add filterprocessor and pprof extension

- content/mentorship.md
- scripts/cspell/project-names.txt
> Add gsoc 2025 member to mentorship.md

- content/docs/next-release-v2/getting-started.md
Fixing docs to match the current state
Tested in local env
> Fixing v2 hotrod directions

- content/docs/next-release-v2/frontend-ui.md
Fixes jaegertracing/jaeger-ui#2092
----
> Document traceIdDisplayLength option

- content/docs/1.6/troubleshooting.md
- content/docs/1.7/troubleshooting.md
- content/docs/1.8/troubleshooting.md
- Fixes #902
- Contributes to prep for #746
> [cleanup] Drop 1.x draft and empty pages

- .github/workflows/ci-test.yml
- Addresses https://github.com/jaegertracing/documentation/pull/903#discussion_r2119752555
> Update ci-test.yml: drop unnecessary `with: submodules`

- themes/jaeger-docs/layouts/partials/home/thanks.html
Added scarf to homepage
make develop and change it.
> Adding scarf to sponsors on bottom of homepage

- content/docs/v2/2.9/deployment/security.md
- content/docs/v2/_dev/deployment/security.md
related to https://github.com/jaegertracing/jaeger/issues/7225
API Key authentication  added in release `2.9.0 `
- 
> Updated elasticsearch auth table

- .cspell/project-names-src.txt
- content/mentorship.md
> Add new mentee for LFX Term 3
